//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATABASEFIRST_EDMX.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_PRODUTOSEntities : DbContext
    {
        public DB_PRODUTOSEntities()
            : base("name=DB_PRODUTOSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NOTA_PRODUTO> NOTA_PRODUTO { get; set; }
        public virtual DbSet<TB_PRODUTOS> TB_PRODUTOS { get; set; }
        public virtual DbSet<TB_TIPO_PRODUTO> TB_TIPO_PRODUTO { get; set; }
    }
}
