//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATABASEFIRST_EDMX.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTA_PRODUTO
    {
        public int IDNOTAPRODUTO { get; set; }
        public int IDPRODUTO { get; set; }
        public int NOTA { get; set; }
    }
}
