//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATABASEFIRST_EDMX.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PRODUTOS
    {
        public int IDPRODUTO { get; set; }
        public string NOMEPRODUTO { get; set; }
        public string DESCRICAOPRODUTO { get; set; }
        public int IDTIPOPRODUTO { get; set; }
        public System.DateTime DATACADASTRO { get; set; }
    
        public virtual TB_TIPO_PRODUTO TB_TIPO_PRODUTO { get; set; }
    }
}
