//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATABASEFIRST_EDMX.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TIPO_PRODUTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_TIPO_PRODUTO()
        {
            this.TB_PRODUTOS = new HashSet<TB_PRODUTOS>();
        }
    
        public int IDTIPOPRODUTO { get; set; }
        public string DESCRICAOTIPOPRODUTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PRODUTOS> TB_PRODUTOS { get; set; }
    }
}
